version: 2

updates:
  # Update PHP to version 8.2.x
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    review:
      # Request a review from the repository owner
      # You can also add multiple reviewers if desired
      reviewers:
        - "ainzone"
      # Wait for a review before merging the pull request
      require-up-to-date: true
    labels:
      - "dependencies"
    package-versions:
      - "php:8.2.*"
