name: Docker Build and Push

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/ainzone/aio-docker-wordpress:latest

      - name: Get the image digest
        id: get_digest
        run: echo "::set-output name=digest::$(docker inspect ghcr.io/ainzone/aio-docker-wordpress:latest --format='{{index .RepoDigests 0}}')"

      - name: Save the image digest
        uses: actions/toolkit@v5
        id: save_digest
        with:
          path: ./digest
          contents: ${{ steps.get_digest.outputs.digest }}
        
      - name: Display the image digest
        run: echo "The image digest is ${{ steps.save_digest.outputs.contents }}"

      - name: Upload the image digest
        uses: actions/upload-artifact@v2
        with:
          name: image-digest
          path: ./digest
          
      - name: Cleanup
        run: |
          rm -rf ./digest